### PR TITLE
add topic paper from Benay Dara-Abrams to RWOT10

### PR DESCRIPTION
**Pull request by benayda**

### CODE REVIEW

**Review by dmitrizagidulin — APPROVED** [review]
Thanks @benayda!

**Comment by benayda** [comment]
Thanks @dmitrizagidulin! Can you tell me what I need to do at this point?

**Comment by jandrieu** [comment]
Please add your paper to the topica and alphabetical listings in the readme.md

**Comment by benayda** [comment]
I have pasted my contributions to the readme file below since the current contents of the readme file have changed beyond the readme version in my fork. At this point, I don't know how to add my contributions to the updated readme file in your repo.
Thanks for your help in adding my paper to the repo and my listings and abstract to the readme file!
Benay
benay@dara-abrams.com

====
### Use Cases

[Sharing Personal Health Data to Improve Treatment of Chronic Conditions](use_case_sharing_personal_health_data_to_improve_treatment_of_chronic_conditions.md)
  * by [Benay Dara-Abrams](mailto:benay@dara-abrams.com)
  * "Believing that no single app or device provides all the information for an individual's health story, Open mHealth is focused on making patient-generated data from disparate sources accessible, developing the IEEE P1752 Standard for Mobile Health Data to harmonize and help make sense of digital health data. I would like to work with others to develop scenarios demonstrating how decentralized digital identity can help in protecting Personally Identifiable Information (PII), Personal Information (PI), and Protected Health 
Information (PHI) while facilitating sharing of personal health data to improve monitoring and treatment of chronic conditions."
  * #use-case #open-mhealth #did #ieee-p1752

Alphabetical Listing

[Sharing Personal Health Data to Improve Treatment of Chronic Conditions](use_case_sharing_personal_health_data_to_improve_treatment_of_chronic_conditions.md)

**Comment by shannona** [comment]
I've merged your PR and added in the contents listings. Thanks!

**Comment by benayda** [comment]
Hi Shannon,

Could you move my paper down into the topics-and-advance-readings
subdirectory? It's up at the root directory of rwot10-buenosaires right
now, so the links from the topic and alphabetical listings aren't pointing
to my paper (use_case_sharing_personal_health_data.. ).

Thanks for your help!
Benay

**Comment by shannona** [comment]
Thanks, Benay. I've done so and it's linked correctly now.

**Pull request merged**
